# This file was automatically generated by Sbtix. Do not edit manually.
{
  "versioning" = [{
      "scalaVersion" = "2.10.6";
      "sbtVersion" = "0.13.15";
    }];
  "repos" = {
    "nix-public" = "";
    "nix-sbt-plugin-releases" = "[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]";
    "nix-typesafe-ivy-releases" = "[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]";
  };
  "artifacts" = {
    "nix-public/biz/aQute/bnd/bndlib/2.1.0/bndlib-2.1.0.jar" = {
      url = "https://repo1.maven.org/maven2/biz/aQute/bnd/bndlib/2.1.0/bndlib-2.1.0.jar";
      sha256 = "0rph1r4nrxrprnwi34m4llzl6s024y629if2yylx7vyj9v23chk6";
    };
    "nix-public/biz/aQute/bnd/bndlib/2.1.0/bndlib-2.1.0.pom" = {
      url = "https://repo1.maven.org/maven2/biz/aQute/bnd/bndlib/2.1.0/bndlib-2.1.0.pom";
      sha256 = "06c5lwvbpgfjk5ccfmfqqbx0rglriyc5rzvx3x4dsxxpgmyd80an";
    };
    "nix-public/biz/aQute/bnd/parent/2.1.0/parent-2.1.0.pom" = {
      url = "https://repo1.maven.org/maven2/biz/aQute/bnd/parent/2.1.0/parent-2.1.0.pom";
      sha256 = "0krm47asbhcqjfwx5zd659xkqiixzjvlpl5i3gwcx16nnw8rw799";
    };
    "nix-public/com/eed3si9n/gigahorse-core_2.10/0.3.0/gigahorse-core_2.10-0.3.0.jar" = {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/gigahorse-core_2.10/0.3.0/gigahorse-core_2.10-0.3.0.jar";
      sha256 = "1wv3h70irpch8v087ibmqzn58as7k4v5cnys0pbhsscn538r7bka";
    };
    "nix-public/com/eed3si9n/gigahorse-core_2.10/0.3.0/gigahorse-core_2.10-0.3.0.pom" = {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/gigahorse-core_2.10/0.3.0/gigahorse-core_2.10-0.3.0.pom";
      sha256 = "10rvzhavhnjal7zzdg1cwhhwry2cj76xppq3aqkknljd3229cbrp";
    };
    "nix-public/com/eed3si9n/gigahorse-okhttp_2.10/0.3.0/gigahorse-okhttp_2.10-0.3.0.jar" = {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/gigahorse-okhttp_2.10/0.3.0/gigahorse-okhttp_2.10-0.3.0.jar";
      sha256 = "1mc2a94363q2n1ra20c23713j14gy2x8m177zm53hy147dqyv6j1";
    };
    "nix-public/com/eed3si9n/gigahorse-okhttp_2.10/0.3.0/gigahorse-okhttp_2.10-0.3.0.pom" = {
      url = "https://repo1.maven.org/maven2/com/eed3si9n/gigahorse-okhttp_2.10/0.3.0/gigahorse-okhttp_2.10-0.3.0.pom";
      sha256 = "1w5l76hbv4nn06fs0arjvm1wig2nnvcv8b3kzhhk4qjzmx6wrhac";
    };
    "nix-public/com/jcraft/jsch/0.1.50/jsch-0.1.50.jar" = {
      url = "https://repo1.maven.org/maven2/com/jcraft/jsch/0.1.50/jsch-0.1.50.jar";
      sha256 = "15di2xp89g3nw4shdmfl6vygqpx57ar8dyrz65d9qhjgx3yfgybx";
    };
    "nix-public/com/jcraft/jsch/0.1.50/jsch-0.1.50.pom" = {
      url = "https://repo1.maven.org/maven2/com/jcraft/jsch/0.1.50/jsch-0.1.50.pom";
      sha256 = "1c5x6zm8yfgbvbxlprlw03nz9m5bpd7n2bsapjnfvp7hbycksvjk";
    };
    "nix-public/com/squareup/okhttp3/okhttp/3.7.0/okhttp-3.7.0.jar" = {
      url = "https://repo1.maven.org/maven2/com/squareup/okhttp3/okhttp/3.7.0/okhttp-3.7.0.jar";
      sha256 = "0rc1g9cj2rkwd0wcpsavj283salvlzgvjhxx8npy2xfs6shbsnpm";
    };
    "nix-public/com/squareup/okhttp3/okhttp/3.7.0/okhttp-3.7.0.pom" = {
      url = "https://repo1.maven.org/maven2/com/squareup/okhttp3/okhttp/3.7.0/okhttp-3.7.0.pom";
      sha256 = "1yxabvdzyr2d232917vbyra8y61zm0zmxy2ak0sy2kgqhqyq16l1";
    };
    "nix-public/com/squareup/okhttp3/parent/3.7.0/parent-3.7.0.pom" = {
      url = "https://repo1.maven.org/maven2/com/squareup/okhttp3/parent/3.7.0/parent-3.7.0.pom";
      sha256 = "0a1rnzsym9rm2hirszyxgr94mx2382880amj20c8k2d79v3w707v";
    };
    "nix-public/com/squareup/okio/okio-parent/1.12.0/okio-parent-1.12.0.pom" = {
      url = "https://repo1.maven.org/maven2/com/squareup/okio/okio-parent/1.12.0/okio-parent-1.12.0.pom";
      sha256 = "157as1rj9qbkpznlipi0s7y7wxfjm2pgsdpd0928k4314b0xvn4k";
    };
    "nix-public/com/squareup/okio/okio/1.12.0/okio-1.12.0.jar" = {
      url = "https://repo1.maven.org/maven2/com/squareup/okio/okio/1.12.0/okio-1.12.0.jar";
      sha256 = "1bli6axdpzxa0b9gxh82g4hvlj5ls33z140ndab3fwf3hgjdzrxz";
    };
    "nix-public/com/squareup/okio/okio/1.12.0/okio-1.12.0.pom" = {
      url = "https://repo1.maven.org/maven2/com/squareup/okio/okio/1.12.0/okio-1.12.0.pom";
      sha256 = "0w24fd8k4q8m37ypcvnr85j706slzxlysiva1pgk2al72y1mcb7g";
    };
    "nix-public/com/thoughtworks/paranamer/paranamer-parent/2.6/paranamer-parent-2.6.pom" = {
      url = "https://repo1.maven.org/maven2/com/thoughtworks/paranamer/paranamer-parent/2.6/paranamer-parent-2.6.pom";
      sha256 = "142n45rzlgjvjmb2aj9r6acvzf07vcfr2knwqxm3lmlanqbxkgjp";
    };
    "nix-public/com/thoughtworks/paranamer/paranamer/2.6/paranamer-2.6.jar" = {
      url = "https://repo1.maven.org/maven2/com/thoughtworks/paranamer/paranamer/2.6/paranamer-2.6.jar";
      sha256 = "1grs2kfh9z5xn5h1z0dqiqbhj5l6k9ww6mbb42n3gzkmin2w2qxr";
    };
    "nix-public/com/thoughtworks/paranamer/paranamer/2.6/paranamer-2.6.pom" = {
      url = "https://repo1.maven.org/maven2/com/thoughtworks/paranamer/paranamer/2.6/paranamer-2.6.pom";
      sha256 = "0jcnwq4yh2nzbsx1x1kvnxrs0xrznjclyfxg31nfrxdq1cqd66q5";
    };
    "nix-public/com/typesafe/config/1.0.0/config-1.0.0.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/config/1.0.0/config-1.0.0.jar";
      sha256 = "1dnsd5gfrlzf259yi9f0937qmz2khqzbrz0bd4kx5w929nkyjr1w";
    };
    "nix-public/com/typesafe/config/1.0.0/config-1.0.0.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/config/1.0.0/config-1.0.0.pom";
      sha256 = "0vg9k4myyx9n5zxylyqspid1c4h14hakkr5fdqrv0bpsqgl0m6i2";
    };
    "nix-public/com/typesafe/config/1.2.0/config-1.2.0.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/config/1.2.0/config-1.2.0.jar";
      sha256 = "0q5xhyyyin4dmw0pnx18lp184msn5ppzmqxib3iv2pxrmklc5wjn";
    };
    "nix-public/com/typesafe/config/1.2.0/config-1.2.0.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/config/1.2.0/config-1.2.0.pom";
      sha256 = "08p5xrn5lkmhrrwfiswdfqjv914b1w11l2jbnywfw2ka9mgjqyh5";
    };
    "nix-public/com/typesafe/mima-core_2.10/0.3.0/mima-core_2.10-0.3.0.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/mima-core_2.10/0.3.0/mima-core_2.10-0.3.0.jar";
      sha256 = "1cn5djfkcqkxx2m3lh79qg1yk1gkapbg8iq2329pwdd5zjq7h7a8";
    };
    "nix-public/com/typesafe/mima-core_2.10/0.3.0/mima-core_2.10-0.3.0.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/mima-core_2.10/0.3.0/mima-core_2.10-0.3.0.pom";
      sha256 = "1x4jz2nqf86js2sivlqm1nxbrh49r70bn5icy4bw0z8sr1wqwn41";
    };
    "nix-public/com/typesafe/mima-reporter_2.10/0.3.0/mima-reporter_2.10-0.3.0.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/mima-reporter_2.10/0.3.0/mima-reporter_2.10-0.3.0.jar";
      sha256 = "1jyya5nw78zx56ji5grq4f4fb2afakhvbwqyhhnffavr2nbahmpl";
    };
    "nix-public/com/typesafe/mima-reporter_2.10/0.3.0/mima-reporter_2.10-0.3.0.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/mima-reporter_2.10/0.3.0/mima-reporter_2.10-0.3.0.pom";
      sha256 = "1y8vlq3j9x2mw87zxnrizgzf51rfr5kbmw41m027bfc9c3z1n9gj";
    };
    "nix-public/com/typesafe/ssl-config-core_2.10/0.2.2/ssl-config-core_2.10-0.2.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/ssl-config-core_2.10/0.2.2/ssl-config-core_2.10-0.2.2.jar";
      sha256 = "0z66w9nf6jkgr0dhyqzy34sxn5fy98hijfbdl29snfy24rpa8268";
    };
    "nix-public/com/typesafe/ssl-config-core_2.10/0.2.2/ssl-config-core_2.10-0.2.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/ssl-config-core_2.10/0.2.2/ssl-config-core_2.10-0.2.2.pom";
      sha256 = "1sslksqki3132xp7hxa2pppqncb891pw1ilava7dwhniqch9qkvn";
    };
    "nix-public/jline/jline/2.14.3/jline-2.14.3.jar" = {
      url = "https://repo1.maven.org/maven2/jline/jline/2.14.3/jline-2.14.3.jar";
      sha256 = "0912i3cn9f357dbk005pv1n0jvyb4s8bz1jspn1jqnvbszzjdp7q";
    };
    "nix-public/jline/jline/2.14.3/jline-2.14.3.pom" = {
      url = "https://repo1.maven.org/maven2/jline/jline/2.14.3/jline-2.14.3.pom";
      sha256 = "1ics4ipmhnz93j0rprydxq306f2zldpywl2xmaqg4mxi38rq1hby";
    };
    "nix-public/org/bouncycastle/bcpg-jdk15on/1.51/bcpg-jdk15on-1.51.jar" = {
      url = "https://repo1.maven.org/maven2/org/bouncycastle/bcpg-jdk15on/1.51/bcpg-jdk15on-1.51.jar";
      sha256 = "0bn6pb9mc0rlimrlr1ssbdxchjcayfiyqygsf2mdw98vw21zcfvd";
    };
    "nix-public/org/bouncycastle/bcpg-jdk15on/1.51/bcpg-jdk15on-1.51.pom" = {
      url = "https://repo1.maven.org/maven2/org/bouncycastle/bcpg-jdk15on/1.51/bcpg-jdk15on-1.51.pom";
      sha256 = "1payl1sl81q4kp4gp021ndsi27xbfl487fb69aqx1q14pbjfa8yn";
    };
    "nix-public/org/bouncycastle/bcprov-jdk15on/1.51/bcprov-jdk15on-1.51.jar" = {
      url = "https://repo1.maven.org/maven2/org/bouncycastle/bcprov-jdk15on/1.51/bcprov-jdk15on-1.51.jar";
      sha256 = "1rvxg8z3ry82xxij8iyga42dzpgxakvkrhd9q4c7ypw9fgng0j47";
    };
    "nix-public/org/bouncycastle/bcprov-jdk15on/1.51/bcprov-jdk15on-1.51.pom" = {
      url = "https://repo1.maven.org/maven2/org/bouncycastle/bcprov-jdk15on/1.51/bcprov-jdk15on-1.51.pom";
      sha256 = "0d3ni711kc8ff2x45pgxyg14c43wjp5d61qjf49vw6jyrn2vpwbh";
    };
    "nix-public/org/codehaus/codehaus-parent/4/codehaus-parent-4.pom" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/codehaus-parent/4/codehaus-parent-4.pom";
      sha256 = "1pqlw2ilzagcl5ahq9dv60cxw59yrvrwf9q6z0679qf2x1yj71vb";
    };
    "nix-public/org/json4s/json4s-ast_2.10/3.2.10/json4s-ast_2.10-3.2.10.jar" = {
      url = "https://repo1.maven.org/maven2/org/json4s/json4s-ast_2.10/3.2.10/json4s-ast_2.10-3.2.10.jar";
      sha256 = "1agaxq0i9gplr932sq5c1raa0da30d83ckyylvqxgxmdf9kr8d8x";
    };
    "nix-public/org/json4s/json4s-ast_2.10/3.2.10/json4s-ast_2.10-3.2.10.pom" = {
      url = "https://repo1.maven.org/maven2/org/json4s/json4s-ast_2.10/3.2.10/json4s-ast_2.10-3.2.10.pom";
      sha256 = "10a5ccin3d6g37qja0g1yip5nbm18xbglbd8g88ml7z810sx48vr";
    };
    "nix-public/org/json4s/json4s-core_2.10/3.2.10/json4s-core_2.10-3.2.10.jar" = {
      url = "https://repo1.maven.org/maven2/org/json4s/json4s-core_2.10/3.2.10/json4s-core_2.10-3.2.10.jar";
      sha256 = "0d2i33ljkk96dyhv799dy198yn4k0ib04qbs7rk616l4mh0fxik3";
    };
    "nix-public/org/json4s/json4s-core_2.10/3.2.10/json4s-core_2.10-3.2.10.pom" = {
      url = "https://repo1.maven.org/maven2/org/json4s/json4s-core_2.10/3.2.10/json4s-core_2.10-3.2.10.pom";
      sha256 = "1fhzpzpx9xk9lx8m3za793qf8kwipc4cs338865z6k3wg8xdhvv9";
    };
    "nix-public/org/jsoup/jsoup/1.7.3/jsoup-1.7.3.jar" = {
      url = "https://repo1.maven.org/maven2/org/jsoup/jsoup/1.7.3/jsoup-1.7.3.jar";
      sha256 = "0zx5lk175aalb32k7f60wgck9923y7nsn8c3aax5chwv15djf25a";
    };
    "nix-public/org/jsoup/jsoup/1.7.3/jsoup-1.7.3.pom" = {
      url = "https://repo1.maven.org/maven2/org/jsoup/jsoup/1.7.3/jsoup-1.7.3.pom";
      sha256 = "138mh2lj7cc67pqpmdcb1va1s9hh5pfmg09qi8rjyc522mkszgpk";
    };
    "nix-public/org/osgi/org.osgi.core/4.2.0/org.osgi.core-4.2.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/osgi/org.osgi.core/4.2.0/org.osgi.core-4.2.0.jar";
      sha256 = "1d78zz118rb08azh1fl7s3apxbfjplrghdgrn0gnn1zar3qzy6pn";
    };
    "nix-public/org/osgi/org.osgi.core/4.2.0/org.osgi.core-4.2.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/osgi/org.osgi.core/4.2.0/org.osgi.core-4.2.0.pom";
      sha256 = "0mv44431pz89s9lqk4c37dz332mizck6n6mkkqlv8ijgv6bww5gh";
    };
    "nix-public/org/reactivestreams/reactive-streams/1.0.0/reactive-streams-1.0.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/reactivestreams/reactive-streams/1.0.0/reactive-streams-1.0.0.jar";
      sha256 = "1sx0kjvzfhqnibvmdq0spjmzrg8lbs7mmdjgqsv6xf8llq17g1pg";
    };
    "nix-public/org/reactivestreams/reactive-streams/1.0.0/reactive-streams-1.0.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/reactivestreams/reactive-streams/1.0.0/reactive-streams-1.0.0.pom";
      sha256 = "065r7nlj7fwckzh0f1g0nnwkw50xbfhixdjzr4ij9wzbc31symd0";
    };
    "nix-public/org/scala-lang/modules/scala-pickling_2.10/0.10.0/scala-pickling_2.10-0.10.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-pickling_2.10/0.10.0/scala-pickling_2.10-0.10.0.jar";
      sha256 = "03jmbspf6w722ajxfbs0xhv54r16g3pwj91ysiilz2x3i8c9v7hm";
    };
    "nix-public/org/scala-lang/modules/scala-pickling_2.10/0.10.0/scala-pickling_2.10-0.10.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-pickling_2.10/0.10.0/scala-pickling_2.10-0.10.0.pom";
      sha256 = "1cvim6mvj3hl5x2q1d8xbjyhnb4lq2qg0ady9y9fsgk1lcbwxpq9";
    };
    "nix-public/org/scala-lang/modules/scala-pickling_2.10/0.10.1/scala-pickling_2.10-0.10.1.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-pickling_2.10/0.10.1/scala-pickling_2.10-0.10.1.jar";
      sha256 = "0p6wa4brziq40vaqacijgg8xn2cpazv1sfngv0h618wnqk4q429y";
    };
    "nix-public/org/scala-lang/modules/scala-pickling_2.10/0.10.1/scala-pickling_2.10-0.10.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-pickling_2.10/0.10.1/scala-pickling_2.10-0.10.1.pom";
      sha256 = "1rc5c9xca1qbqibryv5k8a51pvhf4zpnxcvwrswzwc0afjkynfmw";
    };
    "nix-public/org/scala-lang/scala-compiler/2.10.4/scala-compiler-2.10.4.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.10.4/scala-compiler-2.10.4.jar";
      sha256 = "1i34dfwhwc5i9gdxdr02ilawcnkzsdxbkax91rbrzi12sh4aiyjj";
    };
    "nix-public/org/scala-lang/scala-compiler/2.10.4/scala-compiler-2.10.4.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.10.4/scala-compiler-2.10.4.pom";
      sha256 = "043d3k4mgxbcab005ivnkh7ma93ivqabjyfsy8kd4z7974xkhk74";
    };
    "nix-public/org/scala-lang/scala-compiler/2.10.6/scala-compiler-2.10.6.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.10.6/scala-compiler-2.10.6.jar";
      sha256 = "0fzwhlw9pl92b3mgci85qqz8s0fdci9dyh28lnjcdcjxpqrmjbpb";
    };
    "nix-public/org/scala-lang/scala-compiler/2.10.6/scala-compiler-2.10.6.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.10.6/scala-compiler-2.10.6.pom";
      sha256 = "0spli5785blg6q9rhgh10vgwk01v69zs3ncn1sam5rzbwpkhashi";
    };
    "nix-public/org/scala-lang/scala-compiler/2.10.7/scala-compiler-2.10.7.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.10.7/scala-compiler-2.10.7.jar";
      sha256 = "16k78mrhy698spc7bk3g2hr1hcmrmfbw5flqk35d91766zcm2g9a";
    };
    "nix-public/org/scala-lang/scala-compiler/2.10.7/scala-compiler-2.10.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.10.7/scala-compiler-2.10.7.pom";
      sha256 = "11br9d92zy493ybsfsqllj2mcsfnm2vlr1yr1q1w1nnaxcvq6d6p";
    };
    "nix-public/org/scala-lang/scala-library/2.10.6/scala-library-2.10.6.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.10.6/scala-library-2.10.6.jar";
      sha256 = "0fy2i38z5x4xhw70rlsj33ddg225f15jr9ldbdq3gh59d1fvzqkr";
    };
    "nix-public/org/scala-lang/scala-library/2.10.6/scala-library-2.10.6.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.10.6/scala-library-2.10.6.pom";
      sha256 = "0rr50x93xg480961s0ppyfd5ilcrmdw3rdz29y3dfnrmap99vl34";
    };
    "nix-public/org/scala-lang/scala-library/2.10.7/scala-library-2.10.7.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.10.7/scala-library-2.10.7.jar";
      sha256 = "1rg4jvdkdrj72lpnrlzg247r2k9gc4r43sa8ifqls4gbfgvr64b9";
    };
    "nix-public/org/scala-lang/scala-library/2.10.7/scala-library-2.10.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.10.7/scala-library-2.10.7.pom";
      sha256 = "144ix8i4sl7vg1dzspmnrz1fhc73r7azngx1fzldipzf7xnfyd85";
    };
    "nix-public/org/scala-lang/scala-reflect/2.10.4/scala-reflect-2.10.4.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.10.4/scala-reflect-2.10.4.jar";
      sha256 = "1c5yskzv65n3n58hgggiaqgaxf3w8l31pq5ch6vqfk7ah9lvrbf3";
    };
    "nix-public/org/scala-lang/scala-reflect/2.10.4/scala-reflect-2.10.4.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.10.4/scala-reflect-2.10.4.pom";
      sha256 = "0h5n2fk69xwkliv3xnp8v8n3rpcaiznixdpa9w9raxmrs4wcgf5p";
    };
    "nix-public/org/scala-lang/scala-reflect/2.10.6/scala-reflect-2.10.6.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.10.6/scala-reflect-2.10.6.jar";
      sha256 = "0vgdn6mzzxqwrai1hsjcpsjxqnn38nv1caw6mhmwh3q4zq8jd7xb";
    };
    "nix-public/org/scala-lang/scala-reflect/2.10.6/scala-reflect-2.10.6.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.10.6/scala-reflect-2.10.6.pom";
      sha256 = "1085xmln652gzf3dn2hvyhnfx9pnwsipb54jr5rdxqm30pb1p8i3";
    };
    "nix-public/org/scala-lang/scala-reflect/2.10.7/scala-reflect-2.10.7.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.10.7/scala-reflect-2.10.7.jar";
      sha256 = "15vcil3q5kgwc62mw6inh9rhapxw1m3r7disrg7j1kszqjvwqnmc";
    };
    "nix-public/org/scala-lang/scala-reflect/2.10.7/scala-reflect-2.10.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.10.7/scala-reflect-2.10.7.pom";
      sha256 = "0j5irln44v5qlv15rxbbj773xdk86a504nyy8id54jzv45nfppg0";
    };
    "nix-public/org/scala-sbt/ivy/ivy/2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/ivy/ivy/2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.jar";
      sha256 = "0fcqkj3vg2mfmcjahm2z8wy3lfbgq567n7kkjs8135yiwr0ws6m5";
    };
    "nix-public/org/scala-sbt/ivy/ivy/2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/ivy/ivy/2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4/ivy-2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4.pom";
      sha256 = "0hlkyxivan8wi6vfl19mwppig887qpjdyljjin668zpg6a8hgn2h";
    };
    "nix-public/org/scala-sbt/launcher-interface/1.0.1/launcher-interface-1.0.1.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/launcher-interface/1.0.1/launcher-interface-1.0.1.jar";
      sha256 = "0zby99mp7mf5ra95a0536kl7f8y972a1ldqjhrj88yhw1mgfyxkp";
    };
    "nix-public/org/scala-sbt/launcher-interface/1.0.1/launcher-interface-1.0.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/launcher-interface/1.0.1/launcher-interface-1.0.1.pom";
      sha256 = "0ysandpwxf1rh7dpzxr07a8527sdssx8hqd2396yqw3hwp9jkdrd";
    };
    "nix-public/org/scala-sbt/serialization_2.10/0.1.2/serialization_2.10-0.1.2.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/serialization_2.10/0.1.2/serialization_2.10-0.1.2.jar";
      sha256 = "0n6j469ldrwlhdk9rz95q87ky3wb5m87g9nwlmxb8qvbrlkz37r4";
    };
    "nix-public/org/scala-sbt/serialization_2.10/0.1.2/serialization_2.10-0.1.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/serialization_2.10/0.1.2/serialization_2.10-0.1.2.pom";
      sha256 = "19fw8dlfiy333rdxqnys59nrnn5wj4fmy1srflyrlw6nf0hlfbwm";
    };
    "nix-public/org/scala-sbt/template-resolver/0.1/template-resolver-0.1.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/template-resolver/0.1/template-resolver-0.1.jar";
      sha256 = "0mkw92467i4jip5kbzvl5v1zwzv05alb3hb97l6z9bp641mxbf0b";
    };
    "nix-public/org/scala-sbt/template-resolver/0.1/template-resolver-0.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/template-resolver/0.1/template-resolver-0.1.pom";
      sha256 = "0nsx88y1b3nqpd6r80bb1rpaaskfhcxdbfaqngykrxz8gvq3i2q3";
    };
    "nix-public/org/scala-sbt/test-interface/1.0/test-interface-1.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0.jar";
      sha256 = "17klrl4ylpsy9d16fk6npb7lxfqr1w1m9slsxhph1wwmpcw0pxqm";
    };
    "nix-public/org/scala-sbt/test-interface/1.0/test-interface-1.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0.pom";
      sha256 = "0bknid634xcq5r8fs1bx0ydxs3rhzgmzq1400h7y29n2s2lhdfk1";
    };
    "nix-public/org/scalamacros/quasiquotes_2.10/2.0.1/quasiquotes_2.10-2.0.1.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalamacros/quasiquotes_2.10/2.0.1/quasiquotes_2.10-2.0.1.jar";
      sha256 = "0hmz6viibw9jlzzv30kamp18wb30hlilh6nz6w6xvx8jpzx8f7jq";
    };
    "nix-public/org/scalamacros/quasiquotes_2.10/2.0.1/quasiquotes_2.10-2.0.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalamacros/quasiquotes_2.10/2.0.1/quasiquotes_2.10-2.0.1.pom";
      sha256 = "1b04njqa804m3mf946q92ljb5nqi42cc61xw58r3dhdqvq60gajv";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar";
      sha256 = "0yavwayiv5pkbzvlvmqaaqpxsa9xn9xpcbjr2ywac7awbl4s1i0q";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.pom";
      sha256 = "07hyr3qlsmfkc28b97vzkhx41kq96ns9320l393gsgfrnnhdgnbw";
    };
    "nix-public/org/slf4j/slf4j-parent/1.7.25/slf4j-parent-1.7.25.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-parent/1.7.25/slf4j-parent-1.7.25.pom";
      sha256 = "1ijanlnrs919yk35diwmvayp9l1jr0wqhvqkss46w0yv40hwbx8q";
    };
    "nix-public/org/sonatype/oss/oss-parent/6/oss-parent-6.pom" = {
      url = "https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/6/oss-parent-6.pom";
      sha256 = "16c4i8n978zfb788i6lrwv9b6qgirzqnc25kl5c28fgmx09nsc5l";
    };
    "nix-public/org/sonatype/oss/oss-parent/7/oss-parent-7.pom" = {
      url = "https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/7/oss-parent-7.pom";
      sha256 = "0m4lallnlhyfj3z24ispxzwvsxzaznhw6zsmk4j74sibr5kqh7xm";
    };
    "nix-public/org/sonatype/oss/oss-parent/9/oss-parent-9.pom" = {
      url = "https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/9/oss-parent-9.pom";
      sha256 = "0yl2hbwz2kn1hll1i00ddzn8f89bfdcjwdifz0pj2j15k1gjch7v";
    };
    "nix-public/org/spire-math/jawn-parser_2.10/0.6.0/jawn-parser_2.10-0.6.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/spire-math/jawn-parser_2.10/0.6.0/jawn-parser_2.10-0.6.0.jar";
      sha256 = "0p2g6lcqks4pycv8wr34i6cz9gvv71qv7ngv1rrihgj37jrapcg0";
    };
    "nix-public/org/spire-math/jawn-parser_2.10/0.6.0/jawn-parser_2.10-0.6.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/spire-math/jawn-parser_2.10/0.6.0/jawn-parser_2.10-0.6.0.pom";
      sha256 = "1shmrq62mg2p12sadgwj1bp0yr5fx24byqjw8g5v245syqbgvgri";
    };
    "nix-public/org/spire-math/json4s-support_2.10/0.6.0/json4s-support_2.10-0.6.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/spire-math/json4s-support_2.10/0.6.0/json4s-support_2.10-0.6.0.jar";
      sha256 = "0nilfi5k1smnl3df94xzf2zd6cddisnp8xfyn7mfn4h7r7sq0l0d";
    };
    "nix-public/org/spire-math/json4s-support_2.10/0.6.0/json4s-support_2.10-0.6.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/spire-math/json4s-support_2.10/0.6.0/json4s-support_2.10-0.6.0.pom";
      sha256 = "09x0xr7bvmsbicflz3qzc9fw2afpx9k37y2dwvp46myyscbm1pji";
    };
    "nix-sbt-plugin-releases/com.dwijnand/sbt-compat/scala_2.10/sbt_0.13/1.0.0/ivys/ivy.xml" = {
      url = "https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.dwijnand/sbt-compat/scala_2.10/sbt_0.13/1.0.0/ivys/ivy.xml";
      sha256 = "13dxhj5wqkwy8ynlavricni4qajw36b2hms5h3dcgax15jxksczf";
    };
    "nix-sbt-plugin-releases/com.dwijnand/sbt-compat/scala_2.10/sbt_0.13/1.0.0/jars/sbt-compat.jar" = {
      url = "https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.dwijnand/sbt-compat/scala_2.10/sbt_0.13/1.0.0/jars/sbt-compat.jar";
      sha256 = "0h3aq1ygzlj32zl2wbgfh3anagsh87770iilf4csrf7058823dxq";
    };
    "nix-sbt-plugin-releases/com.jsuereth/pgp-library_2.10/1.1.1/ivys/ivy.xml" = {
      url = "https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.jsuereth/pgp-library_2.10/1.1.1/ivys/ivy.xml";
      sha256 = "0dn4d2xwy5fr9wmqclx9mn6v028vhl8afdqiaxymr71nmn28131f";
    };
    "nix-sbt-plugin-releases/com.jsuereth/pgp-library_2.10/1.1.1/jars/pgp-library_2.10.jar" = {
      url = "https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.jsuereth/pgp-library_2.10/1.1.1/jars/pgp-library_2.10.jar";
      sha256 = "1ix7pp8711r3zvig9kpqkpv270sd552iwyqpxb7mmv49rh0z54hd";
    };
    "nix-sbt-plugin-releases/com.jsuereth/sbt-pgp/scala_2.10/sbt_0.13/1.1.1/ivys/ivy.xml" = {
      url = "https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.jsuereth/sbt-pgp/scala_2.10/sbt_0.13/1.1.1/ivys/ivy.xml";
      sha256 = "1f6h8587cbck0xqc4jl7hrjp1cx1am25x2df1x22xv9c8nxlp1md";
    };
    "nix-sbt-plugin-releases/com.jsuereth/sbt-pgp/scala_2.10/sbt_0.13/1.1.1/jars/sbt-pgp.jar" = {
      url = "https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.jsuereth/sbt-pgp/scala_2.10/sbt_0.13/1.1.1/jars/sbt-pgp.jar";
      sha256 = "0ivvh5z8v1gz0gcrnwxdlir1sprhrsxlq6zbj5q21sx8s6psg6jl";
    };
    "nix-sbt-plugin-releases/com.novocode/sbt-ornate/scala_2.10/sbt_0.13/0.5/ivys/ivy.xml" = {
      url = "https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.novocode/sbt-ornate/scala_2.10/sbt_0.13/0.5/ivys/ivy.xml";
      sha256 = "12w6f3qbvc2z7qnv1z5k00ydmq95ws945mjjqlr7zf3807d6m97j";
    };
    "nix-sbt-plugin-releases/com.novocode/sbt-ornate/scala_2.10/sbt_0.13/0.5/jars/sbt-ornate.jar" = {
      url = "https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.novocode/sbt-ornate/scala_2.10/sbt_0.13/0.5/jars/sbt-ornate.jar";
      sha256 = "13asm0z973ganb3swm95ggp1awg14288xqmcdjgpzhg9h6d7qgqn";
    };
    "nix-sbt-plugin-releases/com.typesafe.sbt/sbt-osgi/scala_2.10/sbt_0.13/0.7.0/ivys/ivy.xml" = {
      url = "https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-osgi/scala_2.10/sbt_0.13/0.7.0/ivys/ivy.xml";
      sha256 = "1q1jh37c91sac646nr893kb3rhssxgj758q7kl86da500237fjly";
    };
    "nix-sbt-plugin-releases/com.typesafe.sbt/sbt-osgi/scala_2.10/sbt_0.13/0.7.0/jars/sbt-osgi.jar" = {
      url = "https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-osgi/scala_2.10/sbt_0.13/0.7.0/jars/sbt-osgi.jar";
      sha256 = "05szndjfnshbzgfg6clfzhy8f0s7bghkga2aqgammqpllx25xy8a";
    };
    "nix-sbt-plugin-releases/com.typesafe/sbt-mima-plugin/scala_2.10/sbt_0.13/0.3.0/ivys/ivy.xml" = {
      url = "https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe/sbt-mima-plugin/scala_2.10/sbt_0.13/0.3.0/ivys/ivy.xml";
      sha256 = "10cjb17wdxcr80lkc88f1psiy2s43pdgslvshg7cnyhb3pf3virb";
    };
    "nix-sbt-plugin-releases/com.typesafe/sbt-mima-plugin/scala_2.10/sbt_0.13/0.3.0/jars/sbt-mima-plugin.jar" = {
      url = "https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe/sbt-mima-plugin/scala_2.10/sbt_0.13/0.3.0/jars/sbt-mima-plugin.jar";
      sha256 = "06cw2m8a1568gjh7m54cp7pwz1gr0fndkq8psgvyjm2kj78794ib";
    };
    "nix-sbt-plugin-releases/com.typesafe/sbt-sdlc/scala_2.10/sbt_0.13/0.1/ivys/ivy.xml" = {
      url = "https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe/sbt-sdlc/scala_2.10/sbt_0.13/0.1/ivys/ivy.xml";
      sha256 = "0kpw47f0hn3hxk577l2r3bcdic65ddqmi2vdw7kj625mv75ygvss";
    };
    "nix-sbt-plugin-releases/com.typesafe/sbt-sdlc/scala_2.10/sbt_0.13/0.1/jars/sbt-sdlc.jar" = {
      url = "https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe/sbt-sdlc/scala_2.10/sbt_0.13/0.1/jars/sbt-sdlc.jar";
      sha256 = "0hnl5jrv1ih7id5n4ibgx4a25473k5b7ca65hykdg9h56fd8ylhw";
    };
    "nix-sbt-plugin-releases/de.johoop/sbt-testng-plugin/scala_2.10/sbt_0.13/3.1.1/ivys/ivy.xml" = {
      url = "https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/de.johoop/sbt-testng-plugin/scala_2.10/sbt_0.13/3.1.1/ivys/ivy.xml";
      sha256 = "198f289x1mqh4zwli8bgvcxl7aghxdijbdghibg9jd9h3irr13fn";
    };
    "nix-sbt-plugin-releases/de.johoop/sbt-testng-plugin/scala_2.10/sbt_0.13/3.1.1/jars/sbt-testng-plugin.jar" = {
      url = "https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/de.johoop/sbt-testng-plugin/scala_2.10/sbt_0.13/3.1.1/jars/sbt-testng-plugin.jar";
      sha256 = "1x3zb82v7j58b0hi7byy4ihz94lah6jczgywvyq00whn252p9v2j";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/actions/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/actions/0.13.15/ivys/ivy.xml";
      sha256 = "077i34n5nps0lr48zq6h43iyr2xicxkr560l5r47ak4vizp0y9gf";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/actions/0.13.15/jars/actions.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/actions/0.13.15/jars/actions.jar";
      sha256 = "0hanwi44rgf5j63bachna7fmsgabn2d4gq9kb196f8y9iknf6va6";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/api/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/api/0.13.15/ivys/ivy.xml";
      sha256 = "142kb4a84070m7pfj7p5cqrapxqzhk2hw6fhhrf5nwmxklf8czac";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/api/0.13.15/jars/api.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/api/0.13.15/jars/api.jar";
      sha256 = "1pnfmfxbhybxn5x5b8v5071h7nxv6sw0fff12r4brkh22c7pyvkj";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/apply-macro/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/apply-macro/0.13.15/ivys/ivy.xml";
      sha256 = "0aivff8qc99jzw7i3yncdxzxmbpjci0bkxla216l63w7izclyshy";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/apply-macro/0.13.15/jars/apply-macro.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/apply-macro/0.13.15/jars/apply-macro.jar";
      sha256 = "188639ddvzw64gp9w64ff9j57v6nlwfc9wrqqsa8rwwxr92n3k89";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/cache/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/cache/0.13.15/ivys/ivy.xml";
      sha256 = "10q7fcmqdvzmixyi14y7pxbhfp4k17nv4ysar2q25f85hklfdb94";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/cache/0.13.15/jars/cache.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/cache/0.13.15/jars/cache.jar";
      sha256 = "01zkiqzxbxl6jq4zcn66q0b5v2nx8sn4415rvv98gs27g6k3vbh1";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/classfile/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/classfile/0.13.15/ivys/ivy.xml";
      sha256 = "0dgwlkqhffp70cihad92rlammrm8hf22aj7snqqv76aaxpl5baip";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/classfile/0.13.15/jars/classfile.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/classfile/0.13.15/jars/classfile.jar";
      sha256 = "0bk0r0hjkknn4zqyamn1hfak316bikvzw3x6mc6p9d35nds4qd7n";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/classpath/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/classpath/0.13.15/ivys/ivy.xml";
      sha256 = "1y7k5napxb54m5191rjky25ljagqwidrlyxx439jhpdbwd733vv1";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/classpath/0.13.15/jars/classpath.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/classpath/0.13.15/jars/classpath.jar";
      sha256 = "1d6j3krn1ykl858njvmznc7m49kszcd4hyx04i0a0zldnsrz44zh";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/collections/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/collections/0.13.15/ivys/ivy.xml";
      sha256 = "1nl6xkch5dfv9nxj0s6gyb7c37yx4pqm7v11c1mz0p69jrbvgq7k";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/collections/0.13.15/jars/collections.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/collections/0.13.15/jars/collections.jar";
      sha256 = "1c489xcmxn2600wfcsl6rk1drwf7qwp3499ka8d66fzc97m41h36";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/command/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/command/0.13.15/ivys/ivy.xml";
      sha256 = "1qmsphfxswclhbhc926zqg7iyx19ilgdswfx9vafns1v7hd1vmps";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/command/0.13.15/jars/command.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/command/0.13.15/jars/command.jar";
      sha256 = "0gg0fhrppmr74gzxbqwjq6xh3v9i61yzsr68id5khhlnhbm5p6w3";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/compile/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compile/0.13.15/ivys/ivy.xml";
      sha256 = "0j2v89gcsqfl7fq5mbmnfmifp6d09zic0aj0g0k79dl6106pqj0p";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/compile/0.13.15/jars/compile.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compile/0.13.15/jars/compile.jar";
      sha256 = "0wd1b3b1g8l11y9qdikl0w0s4qd2hgshgnc2j4a3ypz0dfvgq020";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/compiler-integration/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-integration/0.13.15/ivys/ivy.xml";
      sha256 = "1i2rb08dc1yvy8rqzxcyycnh3zy1m7bk2d06gz46983qgncz089i";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/compiler-integration/0.13.15/jars/compiler-integration.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-integration/0.13.15/jars/compiler-integration.jar";
      sha256 = "1jbcfdahf1af7d6a8h6rxnfjzrfdbm2p20pwvmn8sp79a5bwrgwp";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/compiler-interface/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-interface/0.13.15/ivys/ivy.xml";
      sha256 = "0jzjwls4hcw150xcdc8indfmvd9124vwd2dbnwxnrq0ga2cahxb0";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/compiler-interface/0.13.15/jars/compiler-interface.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-interface/0.13.15/jars/compiler-interface.jar";
      sha256 = "1m8zmm53dmmcrq18fmg8iljgv367s3jsg7acmpg3h87zkna6cgjf";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/compiler-ivy-integration/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-ivy-integration/0.13.15/ivys/ivy.xml";
      sha256 = "0vc30r2mfh3kxy5xvay4yqwbi99i6phw8jgjr7rzrw6ahkdzz83s";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/compiler-ivy-integration/0.13.15/jars/compiler-ivy-integration.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-ivy-integration/0.13.15/jars/compiler-ivy-integration.jar";
      sha256 = "0hjazxg2g7zgh912dj1n79jhgqqpv135x068scrhzv82jjw20rlh";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/completion/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/completion/0.13.15/ivys/ivy.xml";
      sha256 = "08w814igsraq4xi9d5f6rcc1w5ki22fv202xzik8h60xczjark5x";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/completion/0.13.15/jars/completion.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/completion/0.13.15/jars/completion.jar";
      sha256 = "11f3vyzk6xx8iarnpnkmcfsj8rmrik8gmyymd7jdmjjbik7895rp";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/control/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/control/0.13.15/ivys/ivy.xml";
      sha256 = "044s4v0r11r13sds041nzgr8a0v2kmp48w89254zmaaddmw0h2zq";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/control/0.13.15/jars/control.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/control/0.13.15/jars/control.jar";
      sha256 = "0nfi9bhmgqyv3wh64v73pf2vl0pj2mnyknj9r895xgrpr2sck27b";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/core-next_2.10/0.1.1/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/core-next_2.10/0.1.1/ivys/ivy.xml";
      sha256 = "0q7vv3pwcc8n6bmmq5n9y1zdsvjyarrq1xipywv4yaj8hr6bm2q8";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/core-next_2.10/0.1.1/jars/core-next_2.10.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/core-next_2.10/0.1.1/jars/core-next_2.10.jar";
      sha256 = "10bjv67xggzvap4hx5cz9hiwsslwpn96gx349f6n0xdgxpna7yd1";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/cross/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/cross/0.13.15/ivys/ivy.xml";
      sha256 = "14xnkmswqy8brln4jqgcig863ml2a0yyzvm8h5wbd1w3ah62hi96";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/cross/0.13.15/jars/cross.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/cross/0.13.15/jars/cross.jar";
      sha256 = "08bmpwqxhpbypf3lxm1ns2s1fwn6hfz30xl0n3d8lf9slgd8s2k7";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/incremental-compiler/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/incremental-compiler/0.13.15/ivys/ivy.xml";
      sha256 = "1albbxqv13sjbpk6jc37hdai3cz57z7d1jk76p9638xs4wmzdyna";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/incremental-compiler/0.13.15/jars/incremental-compiler.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/incremental-compiler/0.13.15/jars/incremental-compiler.jar";
      sha256 = "145iys4v1bnpbbh4y9xpbk730f0i243amv3x7w22hkikypl7hbli";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/interface/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/interface/0.13.15/ivys/ivy.xml";
      sha256 = "08ipf8zgmrsp6rjy6hi1jiiwqq8dym5fcfggqwm3wz1zdp90iqpa";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/interface/0.13.15/jars/interface.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/interface/0.13.15/jars/interface.jar";
      sha256 = "1arpbcsfjn21r00v1sgyafqdbmirh2q2zdj63rcwxwyw6y6i7g4l";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/io/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/io/0.13.15/ivys/ivy.xml";
      sha256 = "0zfds598bp62vv7vivjxjs1kkpnhgai7km7kdkg6ci2snvx0aija";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/io/0.13.15/jars/io.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/io/0.13.15/jars/io.jar";
      sha256 = "1qn8lnxxvgsv8p004dyq6272r5zxrgz5whf616w4819mxck9aq99";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/ivy/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/ivy/0.13.15/ivys/ivy.xml";
      sha256 = "00byzwf657483fjbb67lzkv9yyvsaw8q8lqcqnc1yhqr4p7cbnr5";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/ivy/0.13.15/jars/ivy.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/ivy/0.13.15/jars/ivy.jar";
      sha256 = "0h9vhhkr0qi5ygkxz7wvsi3g421r0a0amwgv75dmwmdxl25xr6l4";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/logging/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/logging/0.13.15/ivys/ivy.xml";
      sha256 = "0lwrrag9l6dnyxxcc0w3rx7dkws6pcdvrs88xb8bhq5218mlr5n9";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/logging/0.13.15/jars/logging.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/logging/0.13.15/jars/logging.jar";
      sha256 = "1paad0m3cj5kzpxpr1q674shdwr7xaxk6alhn92r6p9ikq5dr53j";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/logic/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/logic/0.13.15/ivys/ivy.xml";
      sha256 = "1hz68kw64an09vr82jql0vis2g7q9675mmn7467i1my7y56bdl3h";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/logic/0.13.15/jars/logic.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/logic/0.13.15/jars/logic.jar";
      sha256 = "1ia8d9ajwgrk91dyj05mh61z84v87pynq2jk46q1fnqlj5dins7j";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/main-settings/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main-settings/0.13.15/ivys/ivy.xml";
      sha256 = "0w3iafa1h70kzzg2mm2h4pds7wchqzbmisnzsj352b3dwq6sg9b7";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/main-settings/0.13.15/jars/main-settings.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main-settings/0.13.15/jars/main-settings.jar";
      sha256 = "0rv93nf83pbr96n1hiqx31f8zc6ghqbwn7gmvxaqaf9msnplfbpw";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/main/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main/0.13.15/ivys/ivy.xml";
      sha256 = "0hh2dgvdkdjkb6482kidlnwsmci84qwml7q69bc2ys2lsf9vabmz";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/main/0.13.15/jars/main.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main/0.13.15/jars/main.jar";
      sha256 = "0c85xawfli71mf52wcxzf4vs68jp0287s3q2fppcn30vgp1pawmw";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/persist/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/persist/0.13.15/ivys/ivy.xml";
      sha256 = "100czcx8lh0nx0s2lpbvl7z06r8swbh5k95ml1x6wy57vgg5p36b";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/persist/0.13.15/jars/persist.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/persist/0.13.15/jars/persist.jar";
      sha256 = "0wlciddm33qg768ihfa88xri0235zg18f8faiv8dmwxz67xpby2k";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/process/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/process/0.13.15/ivys/ivy.xml";
      sha256 = "15w5sm9f5ny1xz2z38zfapanhbcw5pra0989mizgfqrap4bv728r";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/process/0.13.15/jars/process.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/process/0.13.15/jars/process.jar";
      sha256 = "12rnn85sdzrl9gagdz7d747zx5ghj109n0n4xziw2zlrq7h35vjx";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/relation/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/relation/0.13.15/ivys/ivy.xml";
      sha256 = "00ddj6y1gnijs5s3m1bk0i1133gf5c75rs70fjqzrxjdyw2rlwv6";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/relation/0.13.15/jars/relation.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/relation/0.13.15/jars/relation.jar";
      sha256 = "1ga5zx7s9p0jyzr4bamap1zzxqnpvmhky3b7vzdb5gsjgybf4np7";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/run/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/run/0.13.15/ivys/ivy.xml";
      sha256 = "02h1v95fhl8654ydqxqjw4s62dlrfrvmncpvqvz2pgrsk8jjlbsq";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/run/0.13.15/jars/run.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/run/0.13.15/jars/run.jar";
      sha256 = "099r2krnkmfyx0cdm8bylxrxk0znfx8g5rjq0wyh857l915x72hc";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/sbt-core-next/scala_2.10/sbt_0.13/0.1.1/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-core-next/scala_2.10/sbt_0.13/0.1.1/ivys/ivy.xml";
      sha256 = "1v0zg8s4r4jg3xc0qc4v5hzar9znh80vdk4krq26zjrv8rlvyi7g";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/sbt-core-next/scala_2.10/sbt_0.13/0.1.1/jars/sbt-core-next.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-core-next/scala_2.10/sbt_0.13/0.1.1/jars/sbt-core-next.jar";
      sha256 = "00cm3sszvfyp4v227lna5g5dgnss09sqfnhsfxzha5dx55762yjc";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/sbt/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.15/ivys/ivy.xml";
      sha256 = "19r0ppirpxy521q82xy0vq2ky8lsg20ndp14v7nmwpfc2bid6mb5";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/sbt/0.13.15/jars/sbt.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.15/jars/sbt.jar";
      sha256 = "0jqbga8qdv8a2l2amxd6mbyqj16s73biyraan1q5rdkyd3i0s3lh";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/serialization_2.10/0.1.0/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/serialization_2.10/0.1.0/ivys/ivy.xml";
      sha256 = "10i7i4l2m6j60xj5qpsirx6mpfgznv0sycjr3il37a8n45v5jmhn";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/serialization_2.10/0.1.0/jars/serialization_2.10.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/serialization_2.10/0.1.0/jars/serialization_2.10.jar";
      sha256 = "07g7wgr66gahi41sg90f2fgbxz0kz3yhp9q2c7icacpp5cg61jzl";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/task-system/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/task-system/0.13.15/ivys/ivy.xml";
      sha256 = "1778b2hjnwb11rqalbl5sccxhb63q0d139drppw8166mky9hagfs";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/task-system/0.13.15/jars/task-system.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/task-system/0.13.15/jars/task-system.jar";
      sha256 = "0hq0isj2cdzpli4qsdnvbnkc6km0dznv9sr2b84a4pn7kyv47wp2";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/tasks/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/tasks/0.13.15/ivys/ivy.xml";
      sha256 = "1ipnbjjnr2h96rkl04zm7rw4dv27irqnd7dddx6bghj5k67jq20v";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/tasks/0.13.15/jars/tasks.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/tasks/0.13.15/jars/tasks.jar";
      sha256 = "1mr0ahqnx1wwcwk08krpvrvr9nsxwhcwcja91hnyy40gdlj79bjg";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/test-agent/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/test-agent/0.13.15/ivys/ivy.xml";
      sha256 = "0y8ppz2fi8krccr2m3nc7igyqnxll70wchf44ps874a9hjlvlfjn";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/test-agent/0.13.15/jars/test-agent.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/test-agent/0.13.15/jars/test-agent.jar";
      sha256 = "0s7512bzfajqlcm817p6l5gnmi6zp81amhgz527qn6p6m1l85qzb";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/testing/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/testing/0.13.15/ivys/ivy.xml";
      sha256 = "1h50cbpgxmm9fpsiynni0lvhmgs1gdhan3j6k3hah5iv6x1yradk";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/testing/0.13.15/jars/testing.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/testing/0.13.15/jars/testing.jar";
      sha256 = "04bndxmaah5hw60hpplg2lj1sns8f8yi6rpmr33mrsxjamh3vhni";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/tracking/0.13.15/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/tracking/0.13.15/ivys/ivy.xml";
      sha256 = "0wzf37isnh3h748hwcpbr5qglp52jzm9hdpg5c1svyasbsp1856b";
    };
    "nix-typesafe-ivy-releases/org.scala-sbt/tracking/0.13.15/jars/tracking.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/tracking/0.13.15/jars/tracking.jar";
      sha256 = "0fa53k7621xg25zyy9dyd14szvj1w9qrh8pdw6w4pq8vlx5jzfjx";
    };
    "nix-typesafe-ivy-releases/org.scala-tools.sbinary/sbinary_2.10/0.4.2/ivys/ivy.xml" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-tools.sbinary/sbinary_2.10/0.4.2/ivys/ivy.xml";
      sha256 = "1xyjxg6s5nfzb6xjmx5lxcymj79l5gmfcrfk2bnj7ycq7k5hva6g";
    };
    "nix-typesafe-ivy-releases/org.scala-tools.sbinary/sbinary_2.10/0.4.2/jars/sbinary_2.10.jar" = {
      url = "https://repo.typesafe.com/typesafe/ivy-releases/org.scala-tools.sbinary/sbinary_2.10/0.4.2/jars/sbinary_2.10.jar";
      sha256 = "0qhk0ldkkqknqbq5f3gh81f48fpi1fivf1dj880156r80fvrd8nl";
    };
  };
}
